### ISSUE TITLE
Can't test this project

### ISSUE THREAD

**Issue by xan2622** [vraid/earthgen#4]
Hello.

How can I test this project ? 
I can't find any binary .exe file... :(

Please provide instructions about how to launch your planet generator on Windows.
Thanks

**Comment by amitp** [comment]
@x-a-n-a-x This program is written in Racket; it's not a Windows executable. However, even if you had Racket installed, you won't be able to run it, as @vraid has not provided the required libraries (`vraid/flow` and `vraid/opengl` and maybe others).

**Comment by vraid** [comment]
@amitp the libraries are present under package/vraid, but have to be installed in racket manually. Go to File -> Install Package in DrRacket to do this, and the program will run.

**Comment by amitp** [comment]
@vraid doh! I don't know why I didn't find them. Sorry about that!

**Comment by Trigonaut** [comment]
I'd like to try this project out as well, but I'm getting an errorstandard-module-name-resolver: collection not found
  for module path: vraid/flow
  collection: "vraid"
  in collection directories:
   C:\Users\Trigonaut\AppData\Roaming\Racket\6.6\collects
   C:\Program Files\Racket\collects
   ... [162 additional linked and package directories] in: vraid/flow
  no packages suggestions are available .

**Comment by vraid** [comment]
@Trigonaut the main program resides in earthgen.rkt, although all files can be run independently to test their functions.

**Comment by Trigonaut** [comment]
Running earthgen.rkt with DrRacket shows no GUI. The little man in the corner shows it is running, but is there any other step I might have to take to get it to work?
